### PR TITLE
PR segment 2: Add filter vtuber + i18n

### PR DESCRIPTION
**Pull request by LiquidRekto**

### CODE REVIEW

**Comment by LiquidRekto** [comment]
NOTE: Must merge PR Segment 1 First, before merging this! Link >>> https://github.com/vtstats/web/pull/860

**Comment by PoiScript** [comment]
I merged the i18n changes from this pr to main branch, sha: 5dea1eda7ec62c416be46f0a8c026c598eee59df

I moved the remaining to a new branch `feat/retired-filter` with some modifications:

1. `show retired` checkbox is checked by default to maintain existing bahavior,
2. rename `allowRetired` to `showRetired` which makes more sense,
3. remove accordion for simplicity,

I've still encountered some bugs during development, i'll continue working on them tomorrow. keep this pr open for tracking.

**Comment by LiquidRekto** [comment]
Regarding the bug, if it's the selected vtubers count bug, then you can refer right here: https://github.com/vtstats/web/pull/862/commits/ea6bde18c6944e53dfaf33750ea31f5a4224c2a5 (this was in the segment 3)

And for this specific PR, I think I have to let you handle this, since there are so many merge conflicts for me to be able to handle

**Comment by PoiScript** [comment]
merged on 760284a9dd5dc3c2174bde883336eb3a4bacb4e2

**Pull request closed without merging**
